# Generated by Django 3.2.25 on 2024-05-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='catergory',
            new_name='category',
        ),
    ]
